version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  console_err:
    class: logging.StreamHandler
    level: ERROR
    formatter: simple
    stream: ext://sys.stderr
  fileAll:
    class : logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/autoRun.log
    maxBytes: 10240
    backupCount: 3
  fileError:
    class: logging.handlers.RotatingFileHandler
    level: WARN
    formatter: simple
    filename: logs/error.log
    maxBytes: 10240
    backupCount: 3
loggers:
  simpleExample:
    level: DEBUG
    handlers: [console]
    propagate: no
  consoleError:
    level: DEBUG
    handlers: [console_err]
    propagate: no  
  fileExample:
    level: DEBUG
    handlers: [fileAll]
    propagate: no
  debugExample:
    level: DEBUG
    handlers: [fileAll]
    propagate: no  
root:
  level: DEBUG
  handlers: [fileAll,fileError,console]